services:
  php-app:
    build: .
    container_name: php-app
    environment:
      LDAP_HOST: 127.0.0.1
      LDAP_PORT: 389
      LDAP_BASE_DN: dc=example,dc=com
      LDAP_BIND_DN: cn=admin,dc=example,dc=com
      LDAP_BIND_PW: admin
    ports:
      - "8000:80"