version: '3'
services:
  cs:
    container_name: cs-1.6
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=27015
      - MAP=aim_map.bsp
      - MAXPLAYERS=8
      - SV_LAN=1
    ports:
      - "27015:27015/udp"
      - "27015:27015"