services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: Test
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: admin
    volumes:
      - ../../../data/openldap-data/config:/etc/ldap/slapd.d
      - ../../../data/openldap-data/data:/var/lib/ldap
    ports:
      - "389:389"
      - "636:636"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: false
    ports:
      - "8080:80"