services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Test"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
    volumes:
      - ./ldap/config:/etc/ldap/slapd.d
      - ./ldap/data:/var/lib/ldap
    ports:
      - "389:389"
      - "636:636"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: false
    ports:
      - "8080:80"

  php-app:
    build: .
    container_name: php-app
    environment:
      LDAP_HOST: ldap
      LDAP_PORT: 389
      LDAP_BASE_DN: dc=example,dc=com
      LDAP_BIND_DN: cn=admin,dc=example,dc=com
      LDAP_BIND_PW: admin
    ports:
      - "8000:80"
    depends_on:
      - ldap