version: '3'
services:
  service-app:
    container_name: service-nextcloud
    image: nextcloud:fpm
    restart: always
    expose:
      - 80
      - 9000
    volumes:
      - app_data:/var/www/html

  service-onlyoffice:
    container_name: service-onlyoffice
    image: onlyoffice/documentserver:latest
    restart: always
    expose:
      - 80
      - 443
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  service-nginx:
    container_name: service-nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html

  service-mariadb:
    container_name: service-mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloudUser
      MYSQL_PASSWORD: nextcloudPassword
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  service-pma:
    container_name: service-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - service-mariadb:mariadb
    ports:
      - 8081:80
    environment:
      PMA_HOST: mariadb
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootPass

volumes:
  document_data:
  document_log:
  app_data:
  mysql_data: